/*
 * Vesktop, a desktop app aiming to give you a snappier Discord Experience
 * Copyright (c) 2023 Vendicated and Vencord contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import "./themedSplash";
import "./ipcCommands";
import "./appBadge";
import "./fixes";
import "./arrpc";
import "./branding";
import "__patches__"; // auto generated by the build script

export * as Components from "./components";

import { UpdaterIcon, VesktopSettingsIcon } from "@vencord/types/components";

import SettingsUi from "./components/settings/Settings";
import UpdaterUi from "./components/settings/Updater";
import { VesktopLogger } from "./logger";
import { Settings } from "./settings";
export { Settings };

VesktopLogger.log("read if cute :3");
VesktopLogger.log("PhilCord v" + VesktopNative.app.getVersion());

const SettingsPlugin = Vencord.Plugins.plugins
    .Settings as typeof import("@vencord/types/plugins/_core/settings").default;

SettingsPlugin.customEntries.push({
    key: "philcord_updater",
    title: "Updater",
    panelTitle: "PhilCord Updater",
    Component: UpdaterUi,
    Icon: UpdaterIcon
});

SettingsPlugin.customEntries.push({
    key: "vesktop",
    title: "PhilCord",
    panelTitle: "PhilCord Settings",
    Component: SettingsUi,
    Icon: VesktopSettingsIcon
});

const buildSettingsLayout = SettingsPlugin.buildLayout.bind(SettingsPlugin);
SettingsPlugin.buildLayout = function (layoutBuilder) {
    const layout = buildSettingsLayout(layoutBuilder);
    const philCordSection = layout?.find?.((entry: { key?: string }) => entry?.key === "vencord_section");
    if (!philCordSection?.buildLayout) return layout;

    const buildSectionLayout = philCordSection.buildLayout.bind(philCordSection);
    philCordSection.buildLayout = () => {
        const entries = buildSectionLayout();
        const updaterEntry = entries.find((entry: { key?: string }) => entry?.key === "philcord_updater");
        const filteredEntries = entries.filter(
            (entry: { key?: string }) => entry?.key !== "vencord_updater" && entry?.key !== "philcord_updater"
        );

        if (updaterEntry) {
            const themesIndex = filteredEntries.findIndex((entry: { key?: string }) => entry?.key === "vencord_themes");
            filteredEntries.splice(themesIndex + 1, 0, updaterEntry);
        }

        return filteredEntries;
    };

    return layout;
};
