name: Release

on:
    push:
        tags:
            - v*
    workflow_dispatch:

permissions:
    contents: write

jobs:
    release:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v7
            - uses: pnpm/action-setup@v6 # Install pnpm using packageManager key in package.json

            - name: Use Node.js 24
              uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version: 24
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build
              run: pnpm build

            - name: Package and publish PhilCord
              run: pnpm electron-builder --win --publish always
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
